Repository otland/forgottenserver, pull requests merged in 2020-04, with the labels that each got.

#2883 ItemAttributes optimization
  src/item.cpp
  src/item.h
Labels: enhancement

#2902 Added wraping restrictions
  data/events/scripts/player.lua
  data/scripts/actions/others/carpets.lua
Labels: needs-testing

#2924 Added scripts to get afflicted outfit and addons
  data/lib/core/storages.lua
  data/scripts/actions/others/afflicted_outfit.lua
Labels: needs-testing

#2911 Added music box and wild horse
  data/monster/Ungulates/wild_horse.xml
  data/monster/monsters.xml
  data/scripts/actions/others/music_box.lua
  data/scripts/creaturescripts/wild_horse_death.lua
Labels: needs-testing

#2912 Added noxious claw
  data/items/items.xml
  data/movements/movements.xml
  data/scripts/actions/tools/claw_of_the_noxious_spawn.lua
  data/scripts/movements/claw_of_the_noxious_spawn.lua
Labels: needs-testing

#2965 House AccessList: drop support for regular expressions
  src/house.cpp
  src/house.h
Labels: enhancement

#2953 Fix Container::queryMaxCount() bug
  src/player.cpp
Labels: bugfix

#2834 Move events fix
  src/game.cpp
  src/game.h
Labels: bugfix

#2955 Auto stack fix
  src/container.cpp
Labels: bugfix

#2910 Added cup of molten gold action
  data/scripts/actions/others/cup_of_molten_gold.lua
Labels: needs-testing

#2826 allow varying (random) haste / paralyze for monsters
  data/scripts/lib/register_monster_type.lua
  src/luascript.cpp
  src/monsters.cpp
  src/monsters.h
Labels: enhancement, feature, needs-testing

#2966 Fix trade bug
  src/game.cpp
Labels: bugfix

#2970 Player:onTradeCompleted(...)
  data/events/events.xml
  data/events/scripts/player.lua
  src/events.cpp
  src/events.h
  src/game.cpp
Labels: enhancement, feature

#2931 Added flower pot script
  data/scripts/actions/others/flower_pot.lua
  data/scripts/movements/seeds.lua
Labels: needs-testing

#2938 Added nail case script
  data/lib/core/storages.lua
  data/scripts/actions/others/nail_case.lua
Labels: needs-testing

#2935 config: houseOwnedByAccount
  config.lua.dist
  src/configmanager.cpp
  src/configmanager.h
  src/house.cpp
  src/house.h
  src/iologindata.cpp
  src/iologindata.h
Labels: enhancement, feature

#2929 Added swamp digging
  data/actions/lib/actions.lua
  data/lib/core/storages.lua
Labels: needs-testing

#2985 Fix the problem #2983
  data/spells/scripts/house/edit_door_list.lua
  data/spells/spells.xml
Labels: bugfix, needs-testing

#2981 Few monsters fixes
  data/monster/Misc/Misc Mounts/donkey.xml
  data/monster/Sorcerers/incredibly_old_witch.xml
Labels: needs-testing

#2925 Added hive gate teleport script
  data/scripts/actions/others/hive_gate.lua
Labels: needs-testing

#2980 Fix potential memory leak in Game.createMonsterType
  src/luascript.cpp
  src/monsters.cpp
  src/monsters.h
Labels: bugfix, needs-testing

#2937 Added script to Gnomish Voucher items
  data/scripts/actions/others/gnomish_voucher_types.lua
Labels: needs-testing

#2847 Added achievements system
  data/actions/lib/actions.lua
  data/actions/scripts/other/birdcage.lua
  data/actions/scripts/other/blueberrybush.lua
  data/actions/scripts/other/fireworksrocket.lua
  data/actions/scripts/other/largeseashell.lua
  data/actions/scripts/other/music.lua
  data/actions/scripts/other/partyhat.lua
  data/actions/scripts/other/piggybank.lua
  data/actions/scripts/other/potions.lua
  data/actions/scripts/other/wallmirror.lua
  data/actions/scripts/other/windows.lua
  data/actions/scripts/quests/quests.lua
  data/actions/scripts/tools/fishing.lua
  data/actions/scripts/tools/toolgear.lua
  data/lib/core/achievements.lua
  data/lib/core/core.lua
  data/lib/core/storages.lua
  data/movements/scripts/tiles.lua
  data/scripts/actions/others/christmas_bundle.lua
  data/scripts/actions/others/clay_lump.lua
  data/scripts/actions/others/costume_bag.lua
  data/scripts/actions/others/dolls.lua
  data/scripts/actions/others/lottery_ticket.lua
  data/scripts/actions/others/voodoo_doll.lua
  data/scripts/actions/tools/skinning.lua
  data/scripts/creaturescripts/gs_wyda_death.lua
Labels: needs-testing
