Repository otland/forgottenserver, pull requests merged in 2020-05, with the labels that each got.

#2921 Added Ursagrodon taming script
  data/items/items.xml
  data/scripts/actions/others/melting_horn.lua
  data/scripts/actions/others/tinder_box.lua
Labels: needs-testing

#2841 Notify monsters that summon appears
  data/lib/core/creature.lua
  data/lib/core/position.lua
Labels: bugfix

#2973 cmake: tweaks for cmake, vcpkg & CI
  .github/workflows/build-ubuntu.yml
  .github/workflows/build-vcpkg.yml
  .github/workflows/coverity.yml
  .github/workflows/docker-image.yml
  .github/workflows/lua-syntax.yml
  .github/workflows/xml-syntax.yml
  .gitignore
  .travis.yml
  CMakeLists.txt
  Dockerfile
  appveyor.yml
  cmake/FindCXX11.cmake
  cmake/FindGMP.cmake
  cmake/FindLTO.cmake
  cmake/FindLua.cmake
  cmake/FindLuaJIT.cmake
  cmake/FindMySQL.cmake
  cmake/FindPugiXML.cmake
  cmake/cotire.cmake
  data/lib/debugging/lua_version.lua
  data/lib/lib.lua
  src/configmanager.cpp
  src/luascript.h
  src/otserv.cpp
  vc14/theforgottenserver.vcxproj
Labels: enhancement

#3008 actions: fix xmllint
  .github/workflows/xml-syntax.yml
Labels: bugfix

#3006 add missing walkthrough update calls when player level changes
  src/player.cpp
Labels: bugfix

#3007 Include git-based version at compile time
  CMakeLists.txt
  cmake/git_watcher.cmake
  cmake/gitmetadata.h.in
  src/otserv.cpp
Labels: enhancement

#3011 Fix a bug with unnamed containers (normal client)
  src/container.cpp
  src/container.h
  src/item.cpp
Labels: bugfix

#3019 Fixed summoning creature crash in debug mode
  data/lib/core/position.lua
Labels: bugfix

#3018 fix for "speed" on revscriptsys monstertypes
  data/scripts/lib/register_monster_type.lua
Labels: bugfix

#3005 Prevent infinity loop teleports (anti fools)
  src/teleport.cpp
  src/teleport.h
Labels: enhancement

#3020 On Linux, build with gcc and clang
  .github/workflows/build-vcpkg.yml
Labels: enhancement

#3012 Fix disable defense serialization
  src/condition.cpp
  src/condition.h
Labels: bugfix

#2865 Paralyze fixes
  data/spells/spells.xml
  src/spells.cpp
  src/spells.h
Labels: bugfix

#2928 Added taming script
  data/items/items.xml
  data/scripts/actions/others/taming.lua
Labels: needs-testing

#3057 Cleaner and faster XTEA implementation
  src/xtea.cpp
Labels: enhancement

#2815 Immune monsters condition fix
  src/condition.cpp
  src/condition.h
  src/game.cpp
  src/items.cpp
Labels: bugfix

#2877 Fix combat adding conditions
  src/combat.cpp
  src/enums.h
  src/game.cpp
Labels: bugfix

#2545 Fix #2410
  src/condition.cpp
  src/condition.h
  src/enums.h
  src/luascript.cpp
  src/monster.cpp
Labels: bugfix

#3064 Fix container queryAdd issues
  src/container.cpp
  src/player.cpp
Labels: bugfix
