Repository otland/forgottenserver, pull requests merged in 2020-06, with the labels that each got.

#3050 Added Rift Runner mount
  data/lib/core/storages.lua
  data/monster/Arachnids/sparkion.xml
  data/monster/monsters.xml
  data/scripts/actions/others/taming.lua
  data/scripts/actions/others/usable_mount_items.lua
Labels: needs-testing

#2901 [revscriptsys] MoveEvent slot enhancement
  src/luascript.cpp
Labels: needs-testing

#3032 Added insectoid cell
  data/lib/core/storages.lua
  data/scripts/actions/others/insectoid_cell.lua
Labels: needs-testing

#3061 Enable/disable House price on door
  config.lua.dist
  src/configmanager.cpp
  src/configmanager.h
  src/house.cpp
Labels: enhancement

#3062 Use shared_ptr for GuildRank
  src/chat.cpp
  src/guild.cpp
  src/guild.h
  src/house.cpp
  src/iologindata.cpp
  src/luascript.cpp
  src/player.cpp
  src/player.h
Labels: needs-testing

#3066 Added alias keyword function
  data/npc/lib/npcsystem/keywordhandler.lua
  data/npc/scripts/runes.lua
Labels: enhancement

#3024 Items::getItemIdByClientId optimization using vectors
  src/items.cpp
  src/items.h
Labels: enhancement

#3083 Fixed loot tag from captain jones
  data/monster/Bosses/captain_jones.xml
Labels: bugfix

#2990 Kick players while they are attacking or attacked by monsters (when afk)
  src/player.cpp
  src/player.h
Labels: enhancement, needs-testing

#3072 Print duplicate storages
  data/lib/core/storages.lua
Labels: enhancement

#3081 Differentiating hasOutfit from canWear
  src/luascript.cpp
  src/luascript.h
  src/player.cpp
  src/player.h
Labels: enhancement

#2647 Optimized Clean with optional Protection Zone Clean
  config.lua.dist
  src/configmanager.cpp
  src/configmanager.h
  src/game.h
  src/map.cpp
  src/tile.cpp
  src/tile.h
Labels: enhancement

#2728 Small rework on the code for closing a door with a creature in it
  data/actions/scripts/other/doors.lua
  data/lib/core/creature.lua
Labels: needs-testing

#3088 Fix waiting list
  src/protocolgame.cpp
  src/waitlist.cpp
  src/waitlist.h
Labels: bugfix, needs-testing
