Repository otland/forgottenserver, pull requests merged in 2020-11, with the labels that each got.

#3162 Actions updates
  data/actions/actions.xml
  data/actions/scripts/other/bird_cage.lua
  data/actions/scripts/other/blueberry_bush.lua
  data/actions/scripts/other/change_gold.lua
  data/actions/scripts/other/construction_kits.lua
  data/actions/scripts/other/create_bread.lua
  data/actions/scripts/other/decayto.lua
  data/actions/scripts/other/fireworks_rocket.lua
  data/actions/scripts/other/large_seashell.lua
  data/actions/scripts/other/party_hat.lua
  data/actions/scripts/other/piggy_bank.lua
  data/actions/scripts/other/skill_trainer.lua
  data/actions/scripts/other/snow_heap.lua
  data/actions/scripts/other/surprise_bag.lua
  data/actions/scripts/other/transforms.lua
  data/actions/scripts/other/wall_mirror.lua
  data/actions/scripts/other/water_pipe.lua
  data/actions/scripts/tools/tool_gear.lua
  data/items/items.xml
  data/scripts/actions/others/transforms.lua
Labels: needs-testing

#3110 Compat update
  data/global.lua
  data/globalevents/scripts/record.lua
  data/lib/compat/compat.lua
  data/lib/core/player.lua
  data/npc/lib/npcsystem/modules.lua
  data/talkactions/scripts/add_skill.lua
Labels: enhancement, needs-testing

#3137 Many words in talkactions
  data/scripts/talkactions/position.lua
  data/talkactions/talkactions.xml
  src/luascript.cpp
  src/talkaction.cpp
  src/talkaction.h
Labels: decisions
