Repository otland/forgottenserver, pull requests merged in 2020-10, with the labels that each got.

#3160 New container method container:getItems(recursive)
  src/container.cpp
  src/container.h
  src/luascript.cpp
  src/luascript.h
Labels: enhancement

#3189 Add backwards compatibility for pre 1.x loot containers
  src/monsters.cpp
Labels: enhancement

#3132 Multiple words to talkaction RevScript
  data/scripts/talkactions/position.lua
  src/luascript.cpp
  src/spells.cpp
  src/talkaction.cpp
  src/talkaction.h
Labels: enhancement, needs-testing

#3159 Prevent removing items from house if player is not invited
  config.lua.dist
  src/configmanager.cpp
  src/configmanager.h
  src/container.cpp
  src/container.h
  src/cylinder.h
  src/game.cpp
  src/housetile.cpp
  src/housetile.h
  src/mailbox.cpp
  src/mailbox.h
  src/player.cpp
  src/player.h
  src/teleport.cpp
  src/teleport.h
  src/tile.cpp
  src/tile.h
  src/trashholder.cpp
  src/trashholder.h
Labels: enhancement

#2867 Event Callbacks
  data/events/events.xml
  data/events/scripts/creature.lua
  data/events/scripts/monster.lua
  data/events/scripts/party.lua
  data/events/scripts/player.lua
  data/scripts/eventcallbacks/monster/default_onDropLoot.lua
  data/scripts/eventcallbacks/player/default_onLook.lua
  data/scripts/eventcallbacks/player/default_onLookInBattleList.lua
  data/scripts/eventcallbacks/player/default_onMoveItem.lua
  data/scripts/eventcallbacks/player/default_onReportBug.lua
  data/scripts/eventcallbacks/player/default_onReportRuleViolation.lua
  data/scripts/lib/event_callbacks.lua
  data/talkactions/scripts/reload.lua
  src/events.cpp
  src/events.h
  src/game.cpp
  src/luascript.cpp
  src/luascript.h
Labels: needs-testing

#3154 Add some sanity check to spawns
  src/spawn.cpp
Labels: enhancement

#3195 lua52> 'unpack' error fix #3194
  data/lib/compat/compat.lua
  data/scripts/lib/event_callbacks.lua
Labels: bugfix

#2952 tile:remove method
  src/luascript.cpp
  src/luascript.h
  src/map.cpp
  src/map.h
Labels: enhancement, needs-testing

#3186 New store inbox implementation
  data/migrations/25.lua
  data/migrations/26.lua
  schema.sql
  src/CMakeLists.txt
  src/container.cpp
  src/container.h
  src/creature.h
  src/enums.h
  src/game.cpp
  src/housetile.cpp
  src/iologindata.cpp
  src/item.cpp
  src/item.h
  src/items.cpp
  src/items.h
  src/luascript.cpp
  src/luascript.h
  src/player.cpp
  src/player.h
  src/protocolgame.cpp
  src/storeinbox.cpp
  src/storeinbox.h
  src/tile.cpp
  src/tools.cpp
  vc14/theforgottenserver.vcxproj
Labels: bugfix

#3027 Outfit lua metatable
  src/luascript.cpp
  src/luascript.h
  src/outfit.cpp
  src/outfit.h
Labels: enhancement

#2813 Better premium time handling
  data/lib/core/player.lua
  data/migrations/26.lua
  data/migrations/27.lua
  schema.sql
  src/account.h
  src/game.cpp
  src/game.h
  src/iologindata.cpp
  src/iologindata.h
  src/luascript.cpp
  src/luascript.h
  src/player.cpp
  src/player.h
  src/protocolgame.cpp
  src/protocollogin.cpp
Labels: enhancement
