Repository otland/forgottenserver, pull requests merged in 2021-12, with the labels that each got.

#3699 Possibility of defining currencies
  data/actions/actions.xml
  data/actions/scripts/other/change_gold.lua
  data/items/items.xml
  data/lib/core/player.lua
  data/npc/lib/npc.lua
  data/scripts/actions/others/change_gold.lua
  data/scripts/actions/tools/gold_converter.lua
  src/game.cpp
  src/item.cpp
  src/items.cpp
  src/items.h
  src/luascript.cpp
  src/luascript.h
  src/player.cpp
Labels: feature

#3843 feat: special magic level
  src/combat.cpp
  src/item.cpp
  src/items.cpp
  src/items.h
  src/luascript.cpp
  src/movement.cpp
  src/player.h
  src/protocolgame.cpp
Labels: feature

#3794 Updated Visual Studio project file
  vc17/arch32.props
  vc17/arch64.props
  vc17/debug.props
  vc17/release.props
  vc17/settings.props
  vc17/theforgottenserver.ico
  vc17/theforgottenserver.rc
  vc17/theforgottenserver.sln
  vc17/theforgottenserver.vcxproj
Labels: priority: low

#3753 New lua functions for houses
  src/luascript.cpp
  src/luascript.h
Labels: feature

#3860 feature: kill tracking
  data/events/scripts/monster.lua
  data/lib/core/player.lua
Labels: feature

#3854 Fix ProtocolGame::sendModalWindow
  src/protocolgame.cpp
Labels: bugfix

#3740 Fix int_fast16_t overflow
  src/map.cpp
Labels: xmas-sprint

#3845 Quest Tracker feature
  config.lua.dist
  src/configmanager.cpp
  src/configmanager.h
  src/game.cpp
  src/game.h
  src/player.cpp
  src/player.h
  src/protocolgame.cpp
  src/protocolgame.h
  src/quests.cpp
  src/quests.h
Labels: feature
