Repository otland/forgottenserver, pull requests merged in 2021-01, with the labels that each got.

#3252 Use ids under 100 for fluid names
  data/items/items.xml
  src/items.cpp
Labels: enhancement

#3267 Fix mana and life leech bugs
  src/combat.cpp
  src/combat.h
  src/enums.h
Labels: bugfix

#3264 Fix monsters melee attacking
  src/monster.cpp
  src/monster.h
Labels: bugfix

#3272 Don't update monster idle status if it cannot see the creature
  src/monster.cpp
Labels: bugfix

#3249 Add optional params to doTargetCombat/doAreaCombat
  src/combat.h
  src/creature.cpp
  src/creature.h
  src/game.cpp
  src/game.h
  src/luascript.cpp
  src/monster.cpp
  src/monster.h
  src/player.cpp
  src/player.h
Labels: enhancement, feature, needs-testing

#3082 Action grouping
  src/actions.cpp
  src/movement.cpp
Labels: enhancement

#2673 Fix stacking creatures in a tile
  src/game.cpp
  src/luascript.cpp
  src/map.cpp
  src/player.h
  src/protocolgame.cpp
  src/protocolgame.h
  src/tile.cpp
  src/tile.h
Labels: bugfix, needs-testing

#3212 Mwall/WGrowth NoPvp destroy onStepIn
  data/movements/movements.xml
  src/combat.cpp
Labels: feature

#3164 Added random items actions
  data/scripts/actions/others/belongings_of_a_deceased.lua
  data/scripts/actions/others/belongings_of_a_deceased_ravager.lua
  data/scripts/actions/others/belongings_of_a_deceased_shargon.lua
  data/scripts/actions/others/blue_surprise_bag.lua
  data/scripts/actions/others/glooth_bag.lua
  data/scripts/actions/others/gnomish_supply_package.lua
  data/scripts/actions/others/gooey_mass.lua
  data/scripts/actions/others/juicy_root.lua
  data/scripts/actions/others/mysterious_remains.lua
  data/scripts/actions/others/painted_gourd_rattle.lua
  data/scripts/actions/others/peppermoon_bells.lua
  data/scripts/actions/others/red_surprise_bag.lua
  data/scripts/actions/others/shaggy_ogre_bag.lua
  data/scripts/actions/others/surprise_cube.lua
  data/scripts/actions/others/surprise_nest.lua
  data/scripts/actions/others/suspicious_surprise_bag.lua
Labels: needs-testing

#3146 Moved windows and doors to revscriptsys
  data/actions/actions.xml
  data/actions/scripts/other/potions.lua
  data/actions/scripts/other/windows.lua
  data/global.lua
  data/scripts/actions/others/doors.lua
  data/scripts/actions/others/windows.lua
Labels: decisions
