Repository otland/forgottenserver, pull requests merged in 2021-02, with the labels that each got.

#3292 Replace hand-rolled algorithms in spectator container
  src/map.cpp
  src/spectators.h
Labels: enhancement

#3311 Fixed data type mismatch from itemtype
  data/migrations/28.lua
  data/migrations/29.lua
  schema.sql
Labels: bugfix

#3306 Use fused multiply-add for faster & more precise condition/combat calculations
  src/combat.cpp
  src/condition.cpp
  src/condition.h
Labels: enhancement

#3071 Lua-Generated Item descriptions
  data/lib/compat/compat.lua
  data/lib/core/item.lua
  src/configmanager.cpp
  src/configmanager.h
  src/luascript.cpp
  src/luascript.h
Labels: enhancement, feature, needs-testing

#3301 Fix pagination in sendAddContainerItem
  src/player.cpp
Labels: bugfix
