Repository otland/forgottenserver, pull requests merged in 2021-11, with the labels that each got.

#3750 fix disappearing backpack during trade
  src/game.cpp
Labels: bugfix, needs-testing

#3786 #3768 - Fixing use of item on the house door
  src/actions.cpp
Labels: bugfix

#3697 More Readable EventCallback Lib
  data/scripts/lib/event_callbacks.lua
Labels: enhancement

#3776 Set default values on initialization instead of constructor body
  src/enums.h
Labels: enhancement
