Repository otland/forgottenserver, pull requests merged in 2021-08, with the labels that each got.

#3529 Fix saving account storages
  src/game.cpp
Labels: bugfix

#3525 Optimize memory access on XTEA
  src/xtea.cpp
Labels: enhancement

#3530 Use bitset instead of converting u8 to bitset
  src/iologindata.cpp
  src/player.cpp
  src/player.h
Labels: enhancement

#3493 fix spells interaction with walls
  src/combat.cpp
  src/spells.cpp
Labels: bugfix

#3554 fix long double format(from {:d} to {:.2f})
  src/player.cpp
Labels: bugfix

#3556 Fixed Shared Exp Party
  data/events/scripts/party.lua
Labels: bugfix

#3574 Remove insertion operator from lua blessings
  src/luascript.cpp
Labels: bugfix

#3589 Add monster challengeable flag
  data/monster/lua/#example.lua
  data/scripts/lib/register_monster_type.lua
  src/creature.h
  src/luascript.cpp
  src/luascript.h
  src/monster.cpp
  src/monster.h
  src/monsters.cpp
  src/monsters.h
Labels: enhancement

#3542 fix client crashes on "set outfit" window requests
  src/protocolgame.cpp
Labels: needs-testing

#3604 Add monsters walking back to spawn
  config.lua.dist
  src/configmanager.cpp
  src/configmanager.h
  src/game.cpp
  src/luascript.cpp
  src/monster.cpp
  src/position.h
Labels: feature

#3605 Add varying monster spawn
  data/world/forgotten-spawn.xml
  src/spawn.cpp
  src/spawn.h
Labels: feature

#3592 Add monster rename functionality
  src/luascript.cpp
  src/luascript.h
  src/monster.cpp
  src/monster.h
  src/player.h
  src/protocolgame.cpp
  src/protocolgame.h
Labels: feature

#3584 Add attack speed attribute to items.xml
  data/lib/core/item.lua
  src/enums.h
  src/item.cpp
  src/item.h
  src/items.cpp
  src/items.h
  src/luascript.cpp
  src/luascript.h
  src/player.cpp
  src/player.h
  src/tools.cpp
Labels: feature
