Repository otland/forgottenserver, pull requests merged in 2021-07, with the labels that each got.

#2951 condition:getParameter and combat:getParameter methods
  src/combat.cpp
  src/combat.h
  src/condition.cpp
  src/condition.h
  src/luascript.cpp
  src/luascript.h
Labels: feature, needs-testing

#3508 Added A LOT of missing items up to version 10.98
  data/actions/scripts/other/construction_kits.lua
  data/items/items.xml
  data/monster/monsters/black_knight.xml
  data/monster/monsters/bug.xml
  data/monster/monsters/cyclops.xml
  data/monster/monsters/dragon.xml
  data/monster/monsters/dragon_lord.xml
  data/monster/monsters/elf.xml
  data/monster/monsters/elf_arcanist.xml
  data/monster/monsters/elf_scout.xml
  data/monster/monsters/hunter.xml
  data/monster/monsters/orc_berserker.xml
  data/monster/monsters/vampire.xml
Labels: enhancement

#3487 full update on isSightClear
  src/actions.cpp
  src/game.cpp
  src/game.h
  src/map.cpp
  src/map.h
  src/monster.cpp
  src/spells.cpp
Labels: bugfix

#3456 Refactor viewport, move from hardcode
  src/protocolgame.cpp
Labels: enhancement
