Repository otland/forgottenserver, pull requests merged in 2021-06, with the labels that each got.

#3467 feat: add optional drunkenness parameter
  data/scripts/lib/register_monster_type.lua
  src/condition.cpp
  src/condition.h
  src/creature.cpp
  src/creature.h
  src/enums.h
  src/luascript.cpp
  src/luascript.h
  src/monsters.cpp
  src/monsters.h
Labels: enhancement

#3241 Better Corpse Description
  src/creature.cpp
  src/creature.h
  src/player.cpp
Labels: enhancement

#3356 Correct return access talkaction
  src/talkaction.cpp
Labels: decisions

#3489 fix for huge lag caused by incorrect container and addItem
  src/player.cpp
Labels: bugfix
