Repository otland/forgottenserver, pull requests merged in 2022-02, with the labels that each got.

#2807 Adding features from #998
  src/creature.cpp
  src/enums.h
  src/item.cpp
  src/item.h
  src/items.cpp
  src/items.h
  src/luascript.cpp
  src/luascript.h
  src/player.cpp
  src/tools.cpp
Labels: feature

#3923 Fix whereever slot bugs
  src/player.cpp
Labels: bugfix, priority: high

#3912 Add Player:getIdleTime and Player:isNearDepotBox Lua functions
  src/luascript.cpp
  src/luascript.h
  src/player.h
Labels: feature

#3197 Additional checks for unsigned integers to avoid underflow and overflow
  src/luascript.h
Labels: enhancement, decisions

#3934 more detailed shared exp messages
  src/party.cpp
  src/party.h
Labels: enhancement

#3248 Fix trade stacking items
  src/game.cpp
Labels: bugfix

#3863 Moved market description to Lua
  data/events/events.xml
  data/events/scripts/player.lua
  data/lib/core/game.lua
  data/lib/core/itemtype.lua
  data/scripts/eventcallbacks/player/default_onLookInMarket.lua
  data/scripts/lib/event_callbacks.lua
  src/events.cpp
  src/events.h
  src/game.cpp
  src/luascript.cpp
  src/luascript.h
  src/player.h
  src/protocolgame.cpp
  src/protocolgame.h
  src/tools.cpp
  src/tools.h
Labels: enhancement

#3944 Add Player:onInventoryUpdate(item, slot, equip)
  data/events/events.xml
  data/events/scripts/player.lua
  data/scripts/lib/event_callbacks.lua
  src/events.cpp
  src/events.h
  src/player.cpp
Labels: feature

#3858 Added Podium feature
  data/events/events.xml
  data/events/scripts/player.lua
  data/lib/compat/compat.lua
  data/lib/core/core.lua
  data/lib/core/item.lua
  data/lib/core/podium.lua
  data/scripts/actions/others/transforms.lua
  src/CMakeLists.txt
  src/const.h
  src/events.cpp
  src/events.h
  src/game.cpp
  src/game.h
  src/item.cpp
  src/item.h
  src/items.cpp
  src/items.h
  src/luascript.cpp
  src/luascript.h
  src/networkmessage.cpp
  src/player.h
  src/podium.cpp
  src/podium.h
  src/protocolgame.cpp
  src/protocolgame.h
  vc17/theforgottenserver.vcxproj
Labels: feature

#3956 A new way to manage player storages
  data/lib/compat/compat.lua
Labels: feature
