Repository otland/forgottenserver, pull requests merged in 2022-03, with the labels that each got.

#3973 Monster Storages from Lua
  data/scripts/monsters/monster_storages.lua
Labels: feature

#3981 Replace LuaVariant with std::variant
  src/luascript.cpp
  src/luascript.h
  src/luavariant.h
  src/spells.cpp
  src/spells.h
  src/weapons.cpp
  src/weapons.h
Labels: enhancement

#3999 Exp tracker
  config.lua.dist
  src/configmanager.cpp
  src/configmanager.h
  src/luascript.cpp
  src/player.cpp
  src/player.h
  src/protocolgame.cpp
  src/protocolgame.h
Labels: feature

#4004 No need to use pugi::cast let's just use as_string
  src/talkaction.cpp
Labels: bugfix

#4032 Use existing boost algorithms for strings
  src/combat.h
  src/creatureevent.cpp
  src/events.cpp
  src/game.cpp
  src/house.cpp
  src/item.h
  src/items.cpp
  src/luascript.cpp
  src/luascript.h
  src/mailbox.cpp
  src/monsters.cpp
  src/movement.cpp
  src/npc.cpp
  src/otpch.h
  src/otserv.cpp
  src/quests.cpp
  src/raids.cpp
  src/spells.cpp
  src/talkaction.cpp
  src/tools.cpp
  src/tools.h
  src/weapons.cpp
Labels: enhancement
