Repository otland/forgottenserver, pull requests merged in 2023-04, with the labels that each got.

#4283 Remove usages of Game.convertIpToString and mark as deprecated
  data/lib/compat/compat.lua
  data/lib/core/game.lua
  data/scripts/eventcallbacks/player/default_onLook.lua
  data/scripts/eventcallbacks/player/default_onLookInBattleList.lua
  data/talkactions/scripts/info.lua
  data/talkactions/scripts/mc_check.lua
Labels: bugfix

#3848 [Feature] Breakable mana shield
  config.lua.dist
  data/XML/vocations.xml
  data/actions/actions.xml
  data/actions/scripts/others/potions.lua
  data/scripts/spells/cancel_magic_shield.lua
  data/scripts/spells/magic_shield.lua
  data/spells/scripts/support/magic_shield.lua
  data/spells/spells.xml
  src/condition.cpp
  src/condition.h
  src/configmanager.cpp
  src/configmanager.h
  src/enums.h
  src/game.cpp
  src/luascript.cpp
  src/luascript.h
  src/player.h
  src/protocolgame.cpp
  src/vocation.cpp
  src/vocation.h
Labels: feature

#3903 Revscript MonsterType Spell Fixes
  data/monster/lua/#example.lua
  data/scripts/lib/register_monster_type.lua
Labels: bugfix, priority: high

#4393 Fix black square on healing spells
  src/player.cpp
Labels: bugfix

#4427 Extract get killer method in Player:onDeath
  data/creaturescripts/scripts/player_death.lua
Labels: enhancement
