Repository otland/forgottenserver, pull requests merged in 2023-12, with the labels that each got.

#4145 Added Creature:onChangeZone event
  data/events/events.xml
  data/events/scripts/creature.lua
  data/scripts/lib/event_callbacks.lua
  src/creature.cpp
  src/events.cpp
  src/events.h
Labels: feature

#4544 Improve IO ban information
  src/ban.cpp
  src/ban.h
  src/protocolgame.cpp
  src/protocollogin.cpp
Labels: enhancement

#1813 Move raid system to globalevents
  data/lib/compat/compat.lua
  data/lib/core/raids.lua
  data/raids/raids.xml
  data/raids/testraid.xml
  data/scripts/globalevents/#testraid.lua
  data/scripts/globalevents/raids.lua
  data/scripts/globalevents/raids_xml.lua
  data/scripts/talkactions/force_event.lua
  data/talkactions/scripts/force_raid.lua
  data/talkactions/scripts/reload.lua
  data/talkactions/talkactions.xml
  src/CMakeLists.txt
  src/const.h
  src/enums.h
  src/game.cpp
  src/game.h
  src/globalevent.cpp
  src/luascript.cpp
  src/luascript.h
  src/raids.cpp
  src/raids.h
  src/signals.cpp
  src/tools.cpp
  vc17/theforgottenserver.vcxproj
Labels: enhancement

#4538 fix: close parcel send thru mail system to other player
  src/player.cpp
Labels: bugfix

#4613 fix 4612
  data/lib/core/item.lua
  src/combat.cpp
  src/protocolgame.cpp
Labels: bugfix
