Repository otland/forgottenserver, pull requests merged in 2024-12, with the labels that each got.

#4870 Add packet compression
  CMakeLists.txt
  src/CMakeLists.txt
  src/outputmessage.h
  src/protocol.cpp
  src/protocol.h
  src/protocolgame.cpp
  vcpkg.json
Labels: feature

#4880 Use shared_ptr for Inbox
  src/game.cpp
  src/game.h
  src/house.cpp
  src/inbox.h
  src/iomarket.cpp
  src/luascript.cpp
  src/mailbox.cpp
  src/player.cpp
  src/player.h
  src/protocolgame.cpp
Labels: enhancement

#4879 Fix depot memory leak
  src/container.cpp
  src/container.h
  src/cylinder.cpp
  src/cylinder.h
  src/depotchest.h
  src/game.cpp
  src/iologindata.cpp
  src/luascript.cpp
  src/player.cpp
  src/player.h
  src/protocolgame.cpp
Labels: bugfix

#4866 fix monster attack behavior
  src/monster.cpp
Labels: bugfix
