Repository otland/forgottenserver, pull requests merged in 2024-06, with the labels that each got.

#4716 Http login missing VS Project Include files and login problem when on localhost
  src/protocolgame.cpp
  vc17/theforgottenserver.vcxproj
Labels: bugfix

#4720 Set correct minimum dependency versions
  CMakeLists.txt
Labels: enhancement, documentation

#4725 [bugfix] default duration on decaying items with no min or maxvalue set
  src/items.cpp
Labels: bugfix

#4732 [bugfix] fixes bug when player asks to withdraw a string ex; "withdraw" "x"
  data/npc/lib/npc.lua
Labels: bugfix

#4726 Fix use-after-free in creature conditions
  src/creature.cpp
Labels: enhancement, bugfix

#4722 Fix MySQL handle leak
  src/database.cpp
  src/database.h
Labels: bugfix, priority: critical

#4736 Compilation Error issue template update
  .github/ISSUE_TEMPLATE/COMPILATION_REPORT.yml
Labels: documentation

#4724 [Revnpcsys] Revisioned Npc System v1.1
  data/cpplinter.lua
  data/lib/compat/compat.lua
  data/npc/lib/revnpcsys/events.lua
  data/npc/lib/revnpcsys/focus.lua
  data/npc/lib/revnpcsys/handler.lua
  data/npc/lib/revnpcsys/modules.lua
  data/npc/lib/revnpcsys/npc.lua
  data/npc/lib/revnpcsys/requirements.lua
  data/npc/lib/revnpcsys/shop.lua
  data/npc/lib/revnpcsys/talkqueue.lua
  data/npc/lib/revnpcsys/voices.lua
  data/npc/lua/#test.lua
Labels: enhancement, bugfix, revnpcsys

#4718 The Forgotten Server 1.6
  src/definitions.h
Labels: release

#4719 The Forgotten Server 1.7 Development
  src/definitions.h
Labels: development

#4740 Fix some warnings and improve type annotations
  data/cpplinter.lua
  data/events/scripts/player.lua
  data/lib/compat/compat.lua
  data/lib/core/item.lua
  data/scripts/actions/tools/juice_squeezer.lua
  data/scripts/globalevents/raids/raids.lua
  data/spells/scripts/monster/ferumbras_electrify.lua
  data/spells/scripts/monster/glooth_fairy_skill_reducer.lua
  data/spells/scripts/monster/pixie_skill_reducer.lua
Labels: enhancement, documentation

#4741 [Revnpcsys] Revisioned Npc System v1.2
  data/npc/lib/revnpcsys/npc.lua
  src/game.cpp
  src/luascript.cpp
  src/luascript.h
  src/map.h
  src/npc.cpp
  src/npc.h
  src/otserv.cpp
Labels: bugfix, priority: critical, revnpcsys

#4742 [Revscriptsys] fixing memory leak in Actions & Moveevents
  src/actions.cpp
  src/actions.h
  src/luascript.cpp
  src/movement.cpp
  src/movement.h
Labels: enhancement, bugfix, revscriptsys

#4735 Added missing default dependencies for using vcpkg manifest
  vcpkg.json
Labels: enhancement

#4750 [Revscriptsys] fix crash introduced in #4742
  src/actions.cpp
  src/actions.h
  src/luascript.cpp
  src/movement.cpp
  src/movement.h
Labels: bugfix, revscriptsys

#4746 Fix creature icons
  src/protocolgame.cpp
Labels: enhancement

#4747 [Revnpcsys] Revisioned Npc System v1.3
  data/cpplinter.lua
  data/lib/compat/compat.lua
  data/npc/lib/revnpcsys/callbacks.lua
  data/npc/lib/revnpcsys/constants.lua
  data/npc/lib/revnpcsys/events.lua
  data/npc/lib/revnpcsys/focus.lua
  data/npc/lib/revnpcsys/handler.lua
  data/npc/lib/revnpcsys/modules.lua
  data/npc/lib/revnpcsys/npc.lua
  data/npc/lib/revnpcsys/requirements.lua
  data/npc/lib/revnpcsys/shop.lua
  data/npc/lib/revnpcsys/talkqueue.lua
  data/npc/lib/revnpcsys/voices.lua
  data/npc/lua/test.lua
  src/luascript.cpp
  src/luascript.h
  src/npc.cpp
  src/npc.h
  src/protocolgame.cpp
Labels: enhancement, bugfix, revnpcsys

#4730 Remove Account class and account.h file
  src/CMakeLists.txt
  src/account.h
  src/iologindata.cpp
  src/iologindata.h
  src/protocollogin.cpp
  vc17/theforgottenserver.vcxproj
Labels: enhancement
