Repository otland/forgottenserver, pull requests merged in 2024-05, with the labels that each got.

#4664 onDeEquip properly handled at logout/death
  src/player.cpp
Labels: bugfix

#4673 Fix possible crash
  src/creatureevent.cpp
Labels: bugfix

#4674 Fix inverted positions introduced in #4648
  src/combat.cpp
  src/creature.cpp
  src/game.cpp
  src/map.cpp
  src/monster.cpp
  src/npc.cpp
  src/weapons.cpp
Labels: priority: high

#4677 Fix classicAttackSpeed makes server lag (#4676)
  src/player.cpp
  src/player.h
Labels: bugfix

#4668 TextWindow interactive
  data/scripts/creaturescripts/player/#text_window_example.lua
  data/scripts/creaturescripts/player/text_window_helper.lua
Labels: feature

#4683 Bank.lua fix on transfer if params are shifted #4680
  data/npc/scripts/bank.lua
Labels: bugfix

#4672 Annotations & Linter including luascript.cpp functions
  data/cpplinter.lua
Labels: enhancement, feature, documentation

#4576 Simplify logic to select Lua interpreter
  .github/workflows/build-ubuntu.yml
  .github/workflows/build-vcpkg.yml
  .github/workflows/release-vcpkg.yml
  CMakeLists.txt
  Dockerfile
  vcpkg.json
Labels: enhancement

#4693 Fix bank NPC overflow protection being bypassed
  data/npc/lib/npc.lua
Labels: bugfix

#4713 Event callbacks fixes
  data/events/scripts/creature.lua
  data/events/scripts/player.lua
  data/scripts/events/player/default_onUpdateStorage.lua
  data/scripts/lib/event_callbacks.lua
Labels: bugfix

#4671 [Revscriptsys] RevNpcSys version 1.0 (lua npcs / NpcType / new npc system)
  data/cpplinter.lua
  data/lib/compat/compat.lua
  data/lib/core/player.lua
  data/npc/lib/npc.lua
  data/npc/lib/revnpcsys/constants.lua
  data/npc/lib/revnpcsys/events.lua
  data/npc/lib/revnpcsys/focus.lua
  data/npc/lib/revnpcsys/handler.lua
  data/npc/lib/revnpcsys/modules.lua
  data/npc/lib/revnpcsys/npc.lua
  data/npc/lib/revnpcsys/requirements.lua
  data/npc/lib/revnpcsys/shop.lua
  data/npc/lib/revnpcsys/talkqueue.lua
  data/npc/lib/revnpcsys/voices.lua
  data/npc/lua/#test.lua
  data/scripts/lib/create_functions.lua
  data/talkactions/scripts/place_npc.lua
  src/container.cpp
  src/container.h
  src/cylinder.cpp
  src/cylinder.h
  src/game.cpp
  src/luascript.cpp
  src/luascript.h
  src/npc.cpp
  src/npc.h
  src/otserv.cpp
  src/player.cpp
  src/player.h
  src/scriptmanager.cpp
  src/tile.cpp
  src/tile.h
Labels: enhancement, feature

#4715 Templates Update (Bug, Feature, Compilation Error)
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  .github/ISSUE_TEMPLATE/COMPILATION_REPORT.yml
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
Labels: enhancement, documentation

#4706 Minimal HTTP login server
  .github/workflows/test.yml
  CMakeLists.txt
  config.lua.dist
  data/migrations/36.lua
  data/migrations/37.lua
  schema.sql
  src/CMakeLists.txt
  src/base64.cpp
  src/base64.h
  src/configmanager.cpp
  src/configmanager.h
  src/connection.cpp
  src/connection.h
  src/game.cpp
  src/http/CMakeLists.txt
  src/http/cacheinfo.cpp
  src/http/cacheinfo.h
  src/http/error.cpp
  src/http/error.h
  src/http/http.cpp
  src/http/http.h
  src/http/listener.cpp
  src/http/listener.h
  src/http/login.cpp
  src/http/login.h
  src/http/router.cpp
  src/http/router.h
  src/http/session.cpp
  src/http/session.h
  src/http/tests/CMakeLists.txt
  src/http/tests/test_cacheinfo.cpp
  src/http/tests/test_login.cpp
  src/iologindata.cpp
  src/iologindata.h
  src/otserv.cpp
  src/protocolgame.cpp
  src/protocollogin.cpp
  src/tests/CMakeLists.txt
  src/tests/test_base64.cpp
  src/tests/test_generate_token.cpp
  src/tests/test_sha1.cpp
  src/tools.cpp
  src/tools.h
  src/vocation.cpp
  src/vocation.h
  vc17/theforgottenserver.vcxproj
  vcpkg.json
Labels: enhancement, feature, ci-tests
